                                        ; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

(package! go-fill-struct)
(package! evil-easymotion)
(package! evil-snipe)
(package! evil-commentary)
(package! evil-indent-plus)
(package! evil-surround)
(package! protobuf-mode)
(package! makefile-executor)
(package! dockerfile-mode)
(package! browse-at-remote)
(package! groovy-mode)
;; (package! shfmt)
(package! string-inflection)
(package! centered-window)
(package! olivetti)
(package! beacon)
(package! exec-path-from-shell)
(package! closql)
(package! org-preview-html)
(package! transpose-frame)
(package! lsp-grammarly)
(package! disable-mouse)
