;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

(package! go-fill-struct)
(package! evil-easymotion)
(package! evil-snipe)
(package! evil-commentary)
(package! evil-indent-plus)
(package! evil-surround)
(package! protobuf-mode)
(package! makefile-executor)
(package! dockerfile-mode)
(package! browse-at-remote)
(package! groovy-mode)
;; (package! shfmt)
(package! string-inflection)
(package! centered-window)
(package! olivetti)
(package! beacon)
(package! exec-path-from-shell)
(package! closql :pin "0a7226331ff1f96142199915c0ac7940bac4afdd")
